apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: cat-service-config
    files:
      - application.properties

images:
  - name: gcr.io/pgtm-jlong/cat-service # used for Kustomize matching
    newTag: latest
    newName: eduk8s-labs-w01-s089-registry.s1tour-july-prod-86481b7.tanzu-labs.esp.vmware.com
  
